import { Link, Route, Routes, useLocation } from 'react-router-dom';
import { useEffect } from 'react';

const services = [
  ['Website Design','Conversion-ready, compliant websites for every regulated sector','/services/website-design-for-regulated-professional-industries-magneo/'],
  ['SEO for Regulated Industries','Authority-driven organic rankings that respect professional advertising rules','/services/seo-for-regulated-industries/'],
  ['LinkedIn & Social Media','Thought leadership and outreach for regulated professionals','/services/social-media-linkedin-marketing-for-regulated-industries/'],
  ['AI Marketing Automation','Intelligent workflows for lead nurturing, CRM, and pipeline growth','/services/ai-automation-for-regulated-industries-magneo/'],
  ['PPC & Landing Pages','High-intent ad campaigns and compliant landing pages for qualified demand','/services/ppc-landing-pages-for-regulated-industries/'],
  ['Personal Branding','Expert positioning for lawyers, advisors, clinicians, and founders','/services/personal-branding-for-regulated-professionals/']
];

const industries = {
  law:{route:'/law-firm-marketing/',label:'Law Firm Marketing Agency',title:'Marketing that wins clients without crossing the line.',intro:'Compliance-first growth for litigation firms, immigration lawyers, family law practices, employment lawyers, and personal injury firms.',stats:[['160%','More qualified case inquiries'],['Top 3','Legal keyword rankings'],['100%','Compliance-aware workflows'],['6','Core services']],subs:[['Employment Lawyers','/law-firm-marketing/employment-lawyers/'],['Immigration Lawyers','/law-firm-marketing/immigration-lawyers/'],['Family Lawyers','/law-firm-marketing/family-lawyers/'],['Personal Injury Lawyers','/law-firm-marketing/personal-injury-lawyers/'],['Litigation Lawyers','/law-firm-marketing/litigation-lawyers/']]},
  finance:{route:'/financial-firm-marketing/',label:'Financial Firm Marketing Agency',title:'Grow financial trust with clearer authority and safer demand.',intro:'Marketing systems for wealth advisors, portfolio managers, investment firms, insurance advisors, tax advisors, and mutual fund dealers.',stats:[['Top 3','Finance rankings'],['40+','Monthly inquiries'],['100%','Compliance-aware messaging'],['6','Financial verticals']],subs:[['Wealth Advisors','/financial-firm-marketing/marketing-for-wealth-advisors/'],['Insurance Advisors','/financial-firm-marketing/insurance-advisors/'],['Investment Firms','/financial-firm-marketing/investment-firms/'],['Mutual Fund Dealers','/financial-firm-marketing/mutual-fund-dealers/'],['Tax Advisors','/financial-firm-marketing/tax-advisors/'],['Portfolio Managers','/financial-firm-marketing/portfolio-managers/']]},
  healthcare:{route:'/healthcare-marketing/',label:'Healthcare Marketing Agency',title:'Grow patient demand with clarity, privacy, and trust.',intro:'Marketing systems for clinics and providers that improve visibility, simplify patient decisions, and respect healthcare advertising expectations.',stats:[['90%','Patient booking growth'],['11','Healthcare verticals'],['100%','Privacy-aware content'],['Top 3','Local search targets']],subs:[['Aesthetic Clinics','/healthcare-marketing/aesthetic-clinics/'],['Family Medicine Clinics','/healthcare-marketing/family-medicine-clinics/'],['Dental Clinics','/healthcare-marketing/dental-clinics/'],['Fertility Clinics','/healthcare-marketing/fertility-clinic-marketing/'],['Mental Health Clinics','/healthcare-marketing/mental-health-clinics/'],['Dermatology Clinics','/healthcare-marketing/dermatology-clinics/']]},
  tech:{route:'/tech-company-marketing/',label:'Tech Company Marketing Agency',title:'Turn technical credibility into demos, users, and deals.',intro:'Growth systems for FinTech, LegalTech, Crypto, AI, and SaaS companies that need authority, clarity, and demand without hype.',stats:[['70%','Organic lead share'],['5','Tech verticals'],['8-16','Monthly leadership posts'],['100%','Accuracy-first messaging']],subs:[['FinTech Marketing','/tech-company-marketing/fintech-marketing/'],['AI Marketing','/tech-company-marketing/ai-marketing/'],['Crypto Marketing','/tech-company-marketing/crypto-marketing/'],['LegalTech Marketing','/tech-company-marketing/legaltech-marketing/'],['SaaS Marketing','/tech-company-marketing/saas-marketing/']]}
};

const verticals = Object.values(industries).flatMap(i=>i.subs.map(([label,path])=>({label,path,intro:`Magneo builds compliance-aware SEO, website, PPC, LinkedIn, AI automation, and personal branding systems for ${label.toLowerCase()}.`})));
const extraServices = ['seo-for-the-legal-industry','seo-for-financial-advisors-wealth-firms','seo-for-the-healthcare-medtech-industry','ppc-landing-pages-for-law-firms-magneo','ppc-landing-pages-for-financial-advisors-fintech-magneo','ppc-landing-pages-for-healthcare-medtech','social-media-linkedin-leadership-for-healthcare-providers-magneo','social-media-linkedin-leadership-for-tech-saas-ai-companies-magneo','linkedin-growth-law-firms','linkedin-growth-financial-advisors','crypto-and-ai-social-media','website-design-rebrand-for-law-firms-magneo','website-design-for-financial-advisors-wealth-firms-magneo','website-design-for-healthcare-clinics-doctors-magneo','website-design-for-tech-companies-saas-products-magneo','ai-automation-for-law-firms-legal-departments-magneo','ai-automation-for-financial-advisors-firms-fintech-magneo','ai-automation-for-healthcare-providers-clinics-magneo','ai-marketing-automation-for-tech-saas-ai-companies-magneo','personal-branding-for-lawyers-legal-professionals','personal-branding-for-financial-advisors-wealth-professionals','healthcare-medtech'];
const process = [['01','Discovery & Audit','We review your current positioning, search visibility, conversion paths, and compliance constraints.'],['02','Strategy Blueprint','We map the pages, messaging, campaigns, and proof points needed to earn trust and generate demand.'],['03','Execution','We build content, pages, funnels, automation, and reporting around the approved strategy.'],['04','Optimization','We refine based on rankings, qualified inquiries, booked calls, and pipeline quality.']];

function useSeo(title, description, canonical){useEffect(()=>{document.title=title;let m=document.querySelector('meta[name="description"]');if(m)m.content=description;let c=document.querySelector('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c)}c.href=canonical},[title,description,canonical])}
function ScrollTop(){const {pathname}=useLocation();useEffect(()=>scrollTo(0,0),[pathname]);return null}
function Layout({children}){return <><nav className="nav"><div className="container nav-inner"><Link className="brand" to="/">Magneo</Link><div className="nav-links"><Link to="/services/">Services</Link><Link to="/industries/">Industries</Link><Link to="/about/">About</Link><Link to="/contact/">Contact</Link></div><Link className="btn" to="/contact/">Book a call</Link></div></nav><main>{children}</main><Footer/></>}
function Hero({label,title,intro,stat='67',statText='non-blog SEO pages preserved from the current WordPress sitemap.'}){return <section className="hero"><div className="container hero-grid"><div><div className="crumb">Home / {label}</div><div className="label">{label}</div><h1 dangerouslySetInnerHTML={{__html:title}}/><p className="intro">{intro}</p><div className="actions"><Link className="btn" to="/contact/">Request a free audit</Link><Link className="btn outline" to="/services/">Explore services</Link></div></div><div className="glass"><span className="label">Magneo system</span><strong>{stat}</strong><p>{statText}</p></div></div></section>}
function Marquee(){return <div className="marquee">{['SEO','PPC & Landing Pages','Website Design','LinkedIn Growth','AI Automation','Personal Branding','Law Firms','Financial Advisors','Healthcare','Tech & SaaS','Compliance-Safe'].map((x,i)=><span key={i}>{x}</span>)}</div>}
function Home(){useSeo('Magneo | Digital Marketing for Regulated Industries','Authority-first marketing systems for law firms, financial advisors, healthcare providers, and tech companies.','https://magneo.ca/');return <><Hero label="Digital marketing for regulated industries" title={'Marketing that works<br/>in <em>regulated</em><br/>industries.'} intro="Authority-first systems for law firms, financial advisors, healthcare providers, and tech companies. Built to rank, convert, and stay compliant." stat="4" statText="core industry groups served across Canada and the USA."/><Marquee/><Section title="A full growth system for high-trust industries" cards={services}/><IndustryPreview/></>}
function Section({title,cards}){return <section className="section soft"><div className="container"><div className="label">What we do</div><h2>{title}</h2><div className="grid">{cards.map(([t,d,h])=><Link className="card" to={h} key={h}><small>Explore</small><h3>{t}</h3><p>{d}</p></Link>)}</div></div></section>}
function IndustryPreview(){return <section className="section"><div className="container"><div className="label">Industries</div><h2>Built for markets where trust shapes every decision.</h2><div className="grid four">{Object.entries(industries).map(([k,i])=><Link className="card" to={i.route} key={k}><small>{i.subs.length} specializations</small><h3>{i.label}</h3><p>{i.intro}</p></Link>)}</div></div></section>}
function ServicesHub(){useSeo('Services | Magneo','Explore Magneo services for regulated industries.','https://magneo.ca/services/');return <><Hero label="All Services" title={'Every service, built for<br/><em>regulated industries.</em>'} intro="Six core service areas designed around compliance, authority, and measurable ROI." stat="6" statText="core service lines with industry-specific pages."/><Marquee/><section className="section"><div className="container"><div className="label">Six service areas</div><h2>Everything you need to grow in a regulated market.</h2>{services.map(([t,d,h])=><div className="service-card" key={h}><div className="service-head"><div><small className="label">Service</small><h3>{t}</h3><p>{d}</p></div><Link to={h}>View service</Link></div><div className="subgrid">{Object.values(industries).slice(0,4).map(i=><Link className="sub" key={i.label} to={h}><b>{t} for {i.label.replace(' Marketing Agency','')}</b><br/><small>{i.label}</small></Link>)}</div></div>)}</div></section></>}
function IndustriesHub(){useSeo('Industries We Serve | Magneo','Marketing systems for law, finance, healthcare, and technology companies.','https://magneo.ca/industries/');return <><Hero label="Industries we serve" title={'Marketing built for your industry,<br/>not <em>borrowed from another.</em>'} intro="Every industry we serve has its own compliance rules, buyer psychology, and trust signals." stat="22+" statText="industry sub-specializations covered."/><Marquee/><section className="section"><div className="container"><div className="label">Four industry groups</div><h2>Choose your industry to explore tailored strategies.</h2>{Object.entries(industries).map(([k,i])=><div className="service-card" key={k}><div className="service-head"><div><small className="label">{i.subs.length} specializations</small><h3>{i.label}</h3><p>{i.intro}</p></div><Link to={i.route}>View industry</Link></div><div className="subgrid">{i.subs.map(([n,h])=><Link className="sub" to={h} key={h}><b>{n}</b><br/><small>Explore</small></Link>)}</div></div>)}</div></section></>}
function About(){useSeo('About Magneo | Marketing for Regulated Industries','Magneo is a Toronto-based digital marketing agency for regulated industries.','https://magneo.ca/about/');return <><Hero label="About Magneo" title={'Where regulated industries<br/>come to grow safely,<br/>strategically, and <em>fast.</em>'} intro="Magneo is a precision-built growth partner for teams that need more than marketing fluff. They need results they can trust." stat="CA+US" statText="Toronto-based with Canada and USA coverage."/><section className="section"><div className="container"><div className="label">Our purpose</div><h2>Built for industries where precision matters and compliance is non-negotiable.</h2><div className="grid"><div className="card"><h3>Industry-first</h3><p>We start with your rules, buyer psychology, and trust signals before choosing tactics.</p></div><div className="card"><h3>Measurable outcomes</h3><p>We track qualified inquiries, consultations, bookings, and pipeline growth.</p></div><div className="card"><h3>One growth system</h3><p>SEO, PPC, social, automation, design, and branding under one strategy.</p></div></div></div></section><Process/></>}
function IndustryPage({kind}){const i=industries[kind];useSeo(`${i.label} | Magneo`,i.intro,`https://magneo.ca${i.route}`);return <><Hero label={i.label} title={i.title.replace(' without ','<br/>without ').replace(' with ','<br/>with ')} intro={i.intro} stat={i.stats[0][0]} statText={i.stats[0][1]}/><div className="container stats">{i.stats.map(([a,b])=><div key={b}><strong>{a}</strong><span>{b}</span></div>)}</div><section className="section soft"><div className="container"><div className="label">Markets we serve</div><h2>Specialized pages for specific buyer journeys.</h2><div className="grid">{i.subs.map(([n,h])=><Link className="card" to={h} key={h}><small>Explore</small><h3>{n}</h3><p>Strategy, SEO, content, landing pages, and conversion systems tailored to this market.</p></Link>)}</div></div></section><Section title="Every core service, adapted to your compliance reality." cards={services}/><Process/></>}
function Vertical({item}){useSeo(`${item.label} | Magneo`,item.intro,`https://magneo.ca${item.path}`);return <><Hero label={item.label} title={`${item.label}<br/>built for <em>qualified demand.</em>`} intro={item.intro} stat="SEO" statText="Current URL preserved for migration."/><Section title="Recommended services for this market." cards={services}/><Process/></>}
function ServicePage({name}){const clean=(name||'regulated-industries').replace(/-/g,' ').replace(/\bmagneo\b/g,'').replace(/\bseo\b/gi,'SEO').replace(/\bppc\b/gi,'PPC').replace(/\bai\b/gi,'AI');const title=clean.split(' ').map(w=>['for','and','the'].includes(w)?w:w.charAt(0).toUpperCase()+w.slice(1)).join(' ');useSeo(`${title} | Magneo`,`Magneo ${title} service page for regulated industries.`,`https://magneo.ca/services/${name}/`);return <><Hero label="Service" title={`${title}<br/>for <em>regulated markets.</em>`} intro="A compliance-aware service page using Magneo's approved service design pattern, ready for deeper copy expansion." stat="6" statText="core growth channels connected into one system."/><section className="section soft"><div className="container"><div className="label">Who this is for</div><h2>One strategy. Multiple industries, tailored execution.</h2><div className="grid four">{Object.values(industries).map(i=><Link className="card" to={i.route} key={i.label}><small>{i.label}</small><h3>{title}</h3><p>{i.intro}</p></Link>)}</div></div></section><Process/></>}
function Process(){return <section className="section dark"><div className="container"><div className="label">How we work</div><h2>Strategy first, then execution with guardrails.</h2><div className="process">{process.map(([n,t,d])=><div className="process-row" key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>}
function Contact(){useSeo('Contact Magneo | Request a Free Audit','Contact Magneo to request a regulated-industry marketing audit.','https://magneo.ca/contact/');return <><Hero label="Get in touch" title={'Let\'s build something<br/>that <em>actually converts.</em>'} intro="Tell us about your firm, practice, or product. We will review your digital presence and come back with a clear audit." stat="1" statText="business day typical response time."/><section className="section soft"><div className="container"><div className="label">Request a free audit</div><h2>Tell us about your business.</h2><form className="form"><div className="form-row"><label>Full name<input/></label><label>Email<input type="email"/></label></div><div className="form-row"><label>Company<input/></label><label>Website<input/></label></div><div className="form-row"><label>Industry<select><option>Law firm</option><option>Financial services</option><option>Healthcare</option><option>Tech / SaaS</option></select></label><label>Budget<select><option>Not sure yet</option><option>$5k-$10k</option><option>$10k-$25k</option><option>$25k+</option></select></label></div><label>What should we know?<textarea rows="5"/></label><button className="btn" type="submit">Send audit request</button></form></div></section></>}
function Generic({title='Page',path='/'}){useSeo(`${title} | Magneo`,'Magneo React rebuild page preserving the existing SEO route.',`https://magneo.ca${path}`);return <Hero label="Magneo" title={`${title}<br/><em>route preserved.</em>`} intro="This page is preserved in the React migration and ready for final copy expansion." stat="SEO" statText={path}/>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><Link className="brand" to="/">Magneo</Link><p>Digital marketing agency for regulated industries. Toronto, serving Canada and USA.</p></div><div><b>Services</b>{services.slice(0,4).map(s=><Link key={s[2]} to={s[2]}>{s[0]}</Link>)}</div><div><b>Industries</b>{Object.values(industries).map(i=><Link key={i.route} to={i.route}>{i.label}</Link>)}</div><div><b>Company</b><Link to="/about/">About</Link><Link to="/contact/">Contact</Link><Link to="/privacy-policy/">Privacy</Link></div></div></footer>}

export default function App(){return <Layout><ScrollTop/><Routes><Route path="/" element={<Home/>}/><Route path="/services/" element={<ServicesHub/>}/><Route path="/services" element={<ServicesHub/>}/><Route path="/industries/" element={<IndustriesHub/>}/><Route path="/industries" element={<IndustriesHub/>}/><Route path="/about/" element={<About/>}/><Route path="/about" element={<About/>}/><Route path="/our-team/" element={<About/>}/><Route path="/contact/" element={<Contact/>}/><Route path="/contact" element={<Contact/>}/>{Object.entries(industries).map(([k,i])=><Route key={k} path={i.route.replace(/^\//,'').replace(/\/$/,'')} element={<IndustryPage kind={k}/>}/>) }{verticals.map(v=><Route key={v.path} path={v.path.replace(/^\//,'').replace(/\/$/,'')} element={<Vertical item={v}/>}/>) }{services.map(s=><Route key={s[2]} path={s[2].replace(/^\//,'').replace(/\/$/,'')} element={<ServicePage name={s[2].split('/').filter(Boolean).pop()}/>}/>) }{extraServices.map(slug=><Route key={slug} path={`services/${slug}`} element={<ServicePage name={slug}/>}/>) }<Route path="privacy-policy" element={<Generic title="Privacy Policy" path="/privacy-policy/"/>}/><Route path="terms-of-service" element={<Generic title="Terms of Service" path="/terms-of-service/"/>}/><Route path="blog" element={<Generic title="Insights" path="/blog/"/>}/><Route path="*" element={<Home/>}/></Routes></Layout>}
