import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { articles } from './data/related-articles.js';
import './styles/financial-marketing-pages.css';

const BASE='https://magneo.ca';

const financialServices=[
  ['Website design','Clear service pages, professional profiles, and straightforward contact options.','/services/website-design-for-financial-advisors-wealth-firms-magneo/'],
  ['SEO and articles','Search-focused website improvements and useful content based on the services your business provides.','/services/seo-for-financial-advisors-wealth-firms/'],
  ['Social media and video','Educational posts, Reels, and expert-led content developed for selected channels.','/services/linkedin-growth-financial-advisors/'],
  ['PPC and landing pages','Campaigns and focused pages that introduce a specific service or offer.','/services/ppc-landing-pages-for-financial-advisors-fintech/'],
  ['Personal branding and brand voice','Positioning, profile writing, and a consistent way to communicate your expertise.','/services/personal-branding-for-financial-advisors-wealth-professionals/'],
  ['CRM and content automation','Systems for organising enquiries, follow-up tasks, drafts, and approvals.','/services/ai-automation-for-financial-advisors-firms-fintech-magneo/']
];

const process=[
  ['01','Review','Magneo reviews the business, audience, existing materials, and the areas that need attention.'],
  ['02','Scope','The project plan defines the pages, content, campaigns, or workflows to be delivered.'],
  ['03','Production','The agreed work is developed and refined through feedback and designated approvals.'],
  ['04','Delivery and follow-up','Approved work is launched or handed over. Recurring production, reporting, and maintenance follow the selected scope.']
];

const sharedFaqs=[
  ['Can I start with one service?','Yes. A website, content series, campaign, or workflow setup can be scoped as a standalone project.'],
  ['Can you work with our existing marketing team?','Yes. Magneo can support a defined part of production or collaborate around an agreed project, with responsibilities established at the start.'],
  ['Can our team review the material?','Yes. The schedule includes designated feedback and approval stages before the work is published or used.'],
  ['Can you write in our brand voice?','Yes. Existing materials, interviews, and feedback guide the tone and terminology. Brand-voice guidance and custom GPT setup are available where included.'],
  ['How is the project priced?','The proposal defines deliverables, revisions, production requirements, and ongoing support. Advertising spend and third-party software costs are identified separately.'],
  ['Do we need a new website?','Not necessarily. An initial review can identify whether focused improvements or a broader redesign would better address the brief.']
];

const relatedFinancialArticles=[articles.financeContent,articles.financeSocial,articles.advisorEmail,articles.advisorAi];

const pages={
  'insurance-advisors':{
    services:[0,1,2,3,5],
    h1:'Marketing for insurance advisors',title:'Marketing for Insurance Advisors | Magneo',meta:'Websites, educational content, social videos, campaigns, and enquiry workflows for insurance advisors, based on the insurance services they actually provide.',
    description:'Make your services easier to understand before the first conversation. Your website, educational content, social videos and enquiry process can help individuals and business owners understand the types of insurance you advise on and how to get started.',
    cta:'Discuss your insurance-advisor marketing',heading:'Explain the insurance services you actually advise on.',
    copy:'Start with the insurance categories and client groups your business confirms. Clear service information, advisor profiles and practical educational content help visitors understand your approach without assuming every practice offers the same products.',
    cards:[['Actual insurance categories','Build service pages around the types of insurance your practice advises on, using the categories and descriptions your team supplies.'],['Advisor profiles and education','Introduce your advisors accurately and use articles or short videos to answer introductory questions about your services.'],['Enquiries and CRM follow-up','Give visitors a straightforward contact route and organise requests, assignment and follow-up in the CRM workflow your team uses.']],
    faq:['Can campaigns focus on one insurance service?','Yes. The page and campaign can focus on a service your practice offers, with clear information about who it is for and how to request a conversation.']
  },
  'marketing-for-wealth-advisors':{
    services:[0,2,4,5],
    h1:'Marketing for Wealth Advisors',title:'Marketing for Wealth Advisors | Magneo',meta:'Marketing for wealth advisors, including websites, personal branding, educational video, SEO, and campaigns shaped around your advisory approach.',description:'Help prospective clients understand your approach before the first conversation. Magneo develops your website, professional profiles, educational content, and video around the people you serve and the services you provide.',cta:'Discuss your advisor marketing',heading:'Make your advisory approach easier to understand.',copy:'Your public presence should explain who you work with, what your service includes, and how a client relationship begins. Consistent messaging across your website, profiles, and content gives prospective clients and referral partners a clearer introduction to your work.',cards:[['Positioning and profiles','A clear professional introduction, service descriptions, and biographies reflecting your actual experience.'],['Educational content and video','Articles, newsletters, and short videos that explain your approach and answer common introductory questions.'],['Consultation and follow-up','Clear contact options, suitable landing pages, and agreed CRM workflows for managing enquiries.']],project:['A consistent introduction across your channels.','A refreshed advisor biography, clearer service pages, and a recurring video series can communicate the same professional focus across your website and social presence.'],faq:['Can the content focus on a particular client group?','Yes. Messaging and topics can reflect the audience your practice serves, using your actual services and experience as the foundation.']
  },
  'investment-firms':{
    services:[0,1,2,3],
    h1:'Marketing for Investment Firms',title:'Investment Firm Marketing | Magneo',meta:'Marketing for investment firms: positioning, websites, thought leadership, video, and communications developed around your firm’s capabilities.',description:'Present your firm’s capabilities, team, and investment approach with clear, consistent communication. Magneo creates websites, thought-leadership content, and campaigns for the audiences your firm is authorised and equipped to serve.',cta:'Discuss your investment firm’s marketing',heading:'Give your firm a clear and consistent public presence.',copy:'An investment firm’s website needs to explain the organisation, its approach, and the people behind it. Marketing content should make those details accessible while directing different audiences to relevant information.',cards:[['Firm positioning and website','Messaging, team profiles, and capability pages that communicate the organisation’s focus.'],['Thought leadership and communications','Approved commentary, interviews, articles, and email content adapted for the intended audience.'],['Audience-specific pages','Separate information routes where the firm communicates with different client or professional groups.']],project:['A coordinated firm website and content programme.','A clearer firm introduction, updated team pages, and a planned series of approved insights can establish a consistent message across the website and ongoing communications.'],faq:['Can you adapt our existing research or commentary?','Yes. Approved material can be edited and adapted into website articles, email editions, social posts, or video scripts, with review responsibilities agreed.']
  },
  'mutual-fund-dealers':{
    services:[0,2,5],
    h1:'Marketing for Mutual Fund Dealers',title:'Marketing for Mutual Fund Dealers | Magneo',meta:'Websites, advisor profiles, educational content, and review workflows for mutual fund dealers seeking consistent marketing across their organisation.',description:'Keep your organisation’s message consistent across its website, advisor profiles, and educational content. Magneo supports content production and digital presentation, with organised review and distribution workflows where required.',cta:'Discuss your organisation’s marketing',heading:'Consistent content across your organisation.',copy:'A dealer organisation may need shared messaging alongside individual advisor profiles and local information. A defined content structure makes materials easier to maintain and helps each audience find the right introduction or contact.',cards:[['Corporate and advisor pages','Consistent page structures for the organisation, its services, and participating advisors.'],['Reusable content materials','Approved educational articles, email layouts, and social assets that can be adapted within the agreed brand guidance.'],['Review and distribution','Clear stages for feedback, approval, and delivery of the correct content version to the intended team.']],project:['A shared content library for participating advisors.','A set of branded content formats, profile guidance, and an approval workflow can support more consistent communication across the organisation.'],faq:['Can you support several advisors within one brand?','Yes. Shared messaging and reusable formats can be combined with individual profiles, subject to the organisation’s approved responsibilities and review process.']
  },
  'tax-advisors':{
    services:[0,1,2,3],
    h1:'Marketing for Tax Advisors',title:'Marketing for Tax Advisors | Magneo',meta:'Website design, SEO, educational content, and seasonal campaigns for tax advisors. Make your services clearer and enquiries easier to manage.',description:'Make your tax services easy to find and understand throughout the year. Magneo develops websites, search content, educational video, and seasonal campaigns around your actual services and the clients you support.',cta:'Discuss your tax-practice marketing',heading:'Explain the service before the enquiry.',copy:'Visitors need to understand whether your practice provides the type of support they are looking for. Clear service pages and useful introductory content help distinguish individual, business, and specialist services where offered.',cards:[['Service pages and search visibility','Distinct pages for the services the practice provides, with clear descriptions and contact information.'],['Seasonal campaigns','Content and landing pages planned around the practice’s calendar, service availability, and capacity.'],['Year-round expert content','Articles, newsletters, and short videos explaining the practice’s approach and answering common service questions.']],project:['A seasonal campaign with a clear next step.','A focused service page, supporting educational content, and a straightforward booking or enquiry route can introduce a priority service during a planned campaign period.'],faq:['Can marketing continue outside the busiest filing period?','Yes. The content plan can explain year-round services and recurring client questions, based on what the practice actually offers.']
  },
  'portfolio-managers':{
    services:[0,1,2,4],
    h1:'Marketing for Portfolio Managers',title:'Marketing for Portfolio Managers | Magneo',meta:'Marketing for portfolio managers: websites, team profiles, commentary, and expert-led video that explain your philosophy and client approach.',description:'Make your investment philosophy and client relationship easier to understand. Magneo develops websites, professional profiles, commentary, and video that present your team’s approach in clear, consistent language.',cta:'Discuss your portfolio-management marketing',heading:'Explain the thinking behind your approach.',copy:'Your website and content can communicate how the team works, the services available, and what clients can expect from the relationship. A consistent presentation helps readers understand the practice before requesting an introductory conversation.',cards:[['Philosophy and process','Website copy that explains the team’s stated approach using approved information.'],['Team visibility','Profiles, interviews, and expert-led video that introduce the people behind the work.'],['Ongoing communications','Commentary, articles, and newsletters organised into a consistent editorial schedule.']],project:['Turn approved commentary into a connected content series.','An existing commentary piece can provide the foundation for a website article, email edition, short video, and supporting social posts, each adapted to its format.'],faq:['Can you help communicate a technical investment approach clearly?','Yes. Interviews and approved source material help translate the firm’s explanation into accessible copy, with the team reviewing the technical meaning before publication.']
  }
};

export const financialSpecialistSlugs=Object.keys(pages);

function useSeo(title,description,path){useEffect(()=>{document.title=title;let meta=document.querySelector('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.appendChild(meta)}meta.content=description;let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=`${BASE}${path}`},[title,description,path])}

function Hero({page,hub=false}){return <section className="fm-hero"><div className="container"><nav className="fm-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>→</span>{hub?<span>Financial Firm Marketing</span>:<><Link to="/financial-firm-marketing/">Financial Firm Marketing</Link><span>→</span><span>{page.h1.replace('Marketing for ','')}</span></>}</nav><h1>{page.h1}</h1><p>{page.description}</p><div className="fm-actions"><Link className="btn" to="/contact/#contact-enquiry">{page.cta}</Link>{hub&&<a href="#financial-sectors">Find your area of finance</a>}</div></div></section>}

function Services({selected}){const services=selected?selected.map(index=>financialServices[index]):financialServices;if(selected)return <nav className="fm-service-nav" aria-label="Financial-specific services"><div className="container">{services.map(([name,,path])=><Link to={path} key={path}>{name} <span aria-hidden="true">→</span></Link>)}</div></nav>;return <section className="fm-section fm-services" aria-labelledby="fm-services-title"><div className="container"><h2 id="fm-services-title">Choose the support your business needs.</h2><div className="fm-service-grid">{services.map(([name,copy,path])=><Link to={path} key={path}><h3>{name}</h3><p>{copy}</p><span aria-hidden="true">→</span></Link>)}</div></div></section>}

function Process(){return <section className="fm-section fm-process" aria-labelledby="fm-process-title"><div className="container"><h2 id="fm-process-title">From your priorities to finished work.</h2><div className="fm-process-grid">{process.map(([number,title,copy])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>}

function Faq({specific}){const faqs=specific?[...sharedFaqs,specific]:sharedFaqs;return <section className="fm-section fm-faq" aria-labelledby="fm-faq-title"><div className="container"><h2 id="fm-faq-title">Frequently asked questions</h2><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>}

function Related(){return <section className="fm-section fm-related" aria-labelledby="fm-related-title"><div className="container"><h2 id="fm-related-title">Related Articles</h2><ul>{relatedFinancialArticles.map(([title,path])=><li key={path}><a href={path}>{title}</a></li>)}</ul></div></section>}

function Final(){return <section className="fm-section fm-final" aria-labelledby="fm-final-title"><div className="container"><div><h2 id="fm-final-title">Discuss your next marketing priority.</h2><p>Start with the website, content, campaign, or process you want to improve. Magneo can help define a practical scope.</p><Link className="btn" to="/contact/#contact-enquiry">Discuss your project</Link></div></div></section>}

function SectorNav({current}){const links=Object.entries(pages).map(([slug,page])=>[page.h1.replace('Marketing for ',''),`/financial-firm-marketing/${slug}/`]).filter(([,path])=>path!==`/financial-firm-marketing/${current}/`);return <section className="fm-sector-nav" aria-label="Financial sectors"><div className="container"><strong>Financial Firm Marketing</strong><div>{links.map(([name,path])=><Link to={path} key={path}>{name}</Link>)}</div></div></section>}

export function FinancialMarketingHub(){const page={h1:'Marketing for Financial Firms',description:'Websites, educational content, video, and campaigns that make your financial services easier to understand. Magneo develops your messaging and digital presence, with CRM and content workflows available to keep enquiries and marketing activity organised.',cta:'Discuss your firm’s marketing'};useSeo('Financial Firm Marketing Agency | Magneo','Marketing services for financial firms, including websites, educational content, video, campaigns, personal branding, and CRM workflows.','/financial-firm-marketing/');const sectors=[['Wealth advisors','Professional positioning and content that explain your approach and the clients you serve.','/financial-firm-marketing/marketing-for-wealth-advisors/'],['Investment firms','Firm-level messaging, websites, and communications that present your team, capabilities, and investment approach.','/financial-firm-marketing/investment-firms/'],['Mutual fund dealers','Consistent website and educational content across the organisation and its advisor network.','/financial-firm-marketing/mutual-fund-dealers/'],['Tax advisors','Service pages, seasonal campaigns, and useful content that explain your tax practice throughout the year.','/financial-firm-marketing/tax-advisors/'],['Portfolio managers','Clear communication of your investment philosophy, process, team, and client relationship.','/financial-firm-marketing/portfolio-managers/'],['Insurance advisors','Clear service explanations, professional profiles, and educational content for the clients your practice serves.','/financial-firm-marketing/insurance-advisors/']];return <div className="fm-page"><Hero page={page} hub/><section id="financial-sectors" className="fm-section fm-sectors" aria-labelledby="fm-sectors-title"><div className="container"><h2 id="fm-sectors-title">Marketing shaped around your business.</h2><div>{sectors.map(([name,copy,path])=><Link to={path} key={path}><h3>{name}</h3><p>{copy}</p><span aria-hidden="true">→</span></Link>)}</div></div></section><Services/><section className="fm-section fm-voice" aria-labelledby="fm-voice-title"><div className="container"><h2 id="fm-voice-title">Your expertise, in your own voice.</h2><p>Interviews, existing writing, and feedback help establish a consistent tone for your website and content. A custom GPT can support drafting from approved examples, while editing and review shape the final material.</p><p>For expert-led video, the recommended approach puts your team on camera. Topic planning, talking points, and recording guidance help turn familiar subjects into clear explanations.</p></div></section><Process/><Faq/><Related/><Final/></div>}

export function FinancialSpecialistPage({slug}){const page=pages[slug];useSeo(page.title,page.meta,`/financial-firm-marketing/${slug}/`);return <div className="fm-page"><Hero page={page}/><section className="fm-section fm-main" aria-labelledby="fm-main-title"><div className="container"><h2 id="fm-main-title">{page.heading}</h2><p className="fm-intro">{page.copy}</p><div className="fm-main-grid">{page.cards.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div>{page.project&&<aside><span>EXAMPLE PROJECT</span><h3>{page.project[0]}</h3><p>{page.project[1]}</p></aside>}</div></section><Services selected={page.services}/><Process/><Faq specific={page.faq}/><SectorNav current={slug}/><Related/><Final/></div>}
