import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { articles } from './data/related-articles.js';
import './styles/healthcare-marketing-pages.css';

const BASE='https://magneo.ca';

const services=[
  ['Website design and improvements','Clear service pages, practitioner profiles, clinic information, and booking routes that work well on mobile.','/services/website-design-for-healthcare-clinics-doctors-magneo/'],
  ['Local SEO and location pages','Accurate location information and search-focused pages for the services and areas your clinic actually serves.','/services/seo-for-the-healthcare-medtech-industry/'],
  ['Articles, FAQs and educational content','Useful explanations developed from clinic-approved information and reviewed by your designated team.','/services/seo-for-the-healthcare-medtech-industry/'],
  ['Expert-led video, Reels and social media','Practitioner introductions, educational video, and social content selected for the audience and format.','/services/social-media-linkedin-leadership-for-healthcare-providers-magneo/'],
  ['Paid advertising and landing pages','Focused campaigns and landing pages where advertising supports the clinic’s services, capacity, and goals.','/services/ppc-landing-pages-for-healthcare-medtech/'],
  ['CRM and administrative automation','Systems that organise general enquiries, assign follow-up tasks, and manage content approvals without replacing clinical systems.','/services/ai-automation-for-healthcare-providers-clinics-magneo/']
];

const process=[
  ['01','Understand your clinic','Your services, patient access arrangements, capacity and existing website establish the project priorities.'],
  ['02','Plan the improvements','The plan identifies the pages, content, design changes and tools needed to support those priorities.'],
  ['03','Create and review','Website pages, copy and creative content are prepared with clear review points for your team.'],
  ['04','Launch and improve','After launch, reporting follows the agreed goals, such as local visibility, enquiries or completed booking actions.']
];

const commonFaqs=[
  ['Does every project include paid advertising?','No. The scope follows the clinic’s priorities and capacity. A website, local search improvements, content, or an administrative workflow can be completed without an advertising campaign.'],
  ['Who reviews healthcare information?','Your designated clinic reviewer confirms service information, practitioner details, and health-related statements before publication. Marketing support does not replace clinical judgement.'],
  ['Can you work with our current booking system?','Yes. Existing booking links or suitable integrations can be reviewed during planning. The proposal confirms what can be connected and what remains managed by the clinic or its software provider.'],
  ['Does the CRM replace our clinical systems?','No. CRM and automation work described here is for general enquiries, follow-up tasks, and marketing approvals. Clinical records, diagnosis, and care decisions remain in the clinic’s appropriate systems and processes.']
];

const pages={
  'mental-health-clinics':{
    title:'Mental Health Clinic Marketing & Websites | Magneo',meta:'Website design, local SEO, practitioner profiles, and educational content for mental health clinics, with clear enquiry and referral information.',h1:'Marketing for Mental Health Clinics',description:'Help prospective clients understand your services and feel more informed about getting in touch. Website design, local SEO and educational content make your practitioners, areas of focus and enquiry process easier to explore.',heading:'Make the first step easier to understand',cards:[['Practitioner profiles','Practitioner profiles that present qualifications, areas of focus, languages and approach in clear, approachable language.'],['Service and access information','Service and access pages that describe available care, intended clients, session formats, supplied fees and enquiry or referral routes.'],['Educational content','Articles, short videos and answers to common questions developed from your team’s expertise in a consistent clinic voice.']],faq:['Can the website support both direct enquiries and referrals?','Yes. Separate instructions can explain how each route works, which services are available and what the next step involves. The wording follows your clinic’s actual access arrangements.'],serviceOrder:[0,1,2,3,5,4]
  },
  'chiropractic-clinics':{
    title:'Chiropractic Marketing & Website Design | Magneo',meta:'Website design, local SEO, first-visit information, and clinic content for chiropractic practices seeking a clearer local presence.',h1:'Marketing for Chiropractic Clinics',description:'Give local patients a clear introduction to your clinic. A professional website, accurate local listings and useful content explain your services, introduce your team and make booking information easy to find.',heading:'From local search to a clear first visit',cards:[['Local visibility','A website and local listings that present the right location, hours and contact details consistently.'],['First-visit information','First-visit pages that explain preparation, booking and what patients can expect, using information supplied by your clinic.'],['Clinic content and video','Practitioner introductions, articles, short videos and social content that answer common patient questions.']],faq:['Can you improve an existing chiropractic website?','Yes. The project can focus on clearer service pages, practitioner profiles, mobile usability, local search and booking links, or include a full redesign where needed.'],serviceOrder:[1,0,2,3,5,4]
  },
  'family-medicine-clinics':{
    title:'Family Medicine Websites & Clinic Marketing | Magneo',meta:'Websites, local listings, patient information, and clinic updates for family medicine practices serving new or existing patients.',h1:'Websites and Marketing for Family Medicine Clinics',description:'Give patients a reliable place to find clinic information. Clear websites, accurate local listings and useful updates explain your services, booking options and new-patient availability.',heading:'A useful website, even when your practice is full',cards:[['Clear booking and registration information','Booking and registration pages with a clearly visible contact route.'],['Current new-patient availability','Editable intake information that shows whether the clinic is accepting new patients.'],['Opening hours, locations and contact options','Website and listing details that bring hours, locations and contact options together.'],['Service information and common administrative questions','Service pages and administrative FAQs that answer recurring non-clinical questions in one reliable place.'],['Clinic announcements and website updates','Clinic announcements and an update process your team can manage.']],faq:['Is marketing useful if the clinic is not accepting new patients?','Yes. The priority can be a clearer website, accurate search listings and better information for existing patients. Campaigns for new patients are only relevant when they support your clinic’s capacity and plans.'],serviceOrder:[0,1,2,5,3,4]
  },
  'aesthetic-clinics':{
    title:'Aesthetic Clinic Marketing & Websites | Magneo',meta:'Website design, treatment education, search marketing, video, and consultation campaigns for aesthetic clinics.',h1:'Marketing for Aesthetic Clinics',description:'Help prospective clients understand your treatments and choose an informed next step. Website design, search marketing and video content bring your services, practitioners and consultation process into focus.',heading:'Give prospective clients more useful information',cards:[['Treatment pages','Treatment pages that explain each service, the consultation process and questions to discuss with the practitioner.'],['Practitioner and clinic introductions','Genuine team profiles, clinic photography and expert-led video that introduce the people behind the service.'],['Consultation campaigns','Focused landing pages and relevant campaigns with a clear way to request a consultation.']],faq:['Can you create treatment videos and social content?','Yes. Content can include practitioner explanations, clinic introductions, treatment FAQs and short videos adapted for the selected platforms. Your team reviews treatment information before publication.'],serviceOrder:[0,3,2,1,4,5]
  },
  'physiotherapy-clinics':{
    title:'Physiotherapy Marketing & Website Design | Magneo',meta:'Website design, local SEO, service pages, and assessment information for physiotherapy clinics and their genuine locations.',h1:'Marketing for Physiotherapy Clinics',description:'Help people find your clinic and understand the services available. Local SEO, clear service pages and educational content introduce your team and make assessment booking information easier to follow.',heading:'Explain the care available at your clinic',cards:[['Service pages','Service pages organised around the clinic’s actual offerings, practitioner information and relevant booking options.'],['Location visibility','Location pages and listings with accurate contact information, hours and directions for genuine clinic locations.'],['Assessment information','Assessment pages that explain first-visit preparation and the clinic’s supplied referral or coverage information.']],faq:['Can the website explain different physiotherapy services?','Yes. Separate pages can introduce the services your clinic actually offers, the practitioners providing them and how to arrange an assessment. The structure follows your practice rather than a generic list of treatments.'],serviceOrder:[1,0,2,3,4,5]
  },
  'dental-clinics':{
    title:'Dental Marketing & Website Design | Magneo',meta:'Website design, local SEO, new-patient information, educational content, and focused campaigns for dental clinics.',h1:'Marketing for Dental Clinics',description:'Help local patients get to know your practice before they contact you. Website design, local SEO and educational content explain your dental services, introduce your team and make new-patient booking information easy to find.',heading:'A clearer introduction to your dental practice',cards:[['New-patient information','New-patient pages that explain registration, the first visit and available booking options.'],['Service and team pages','Dentist profiles and service pages written in language patients can understand.'],['Local search and campaigns','Local-search improvements and relevant campaigns connected to service pages and a clear contact option.']],faq:['Can campaigns focus on selected dental services?','Yes. Campaigns and landing pages can focus on services your practice wants to promote, with messaging and booking options matched to those services and your capacity.'],serviceOrder:[1,0,2,4,3,5]
  }
};

export const healthcareSpecialistSlugs=Object.keys(pages);
export const healthcareSpecialistSearchDescription=(slug)=>pages[slug]?.meta||pages[slug]?.description;
const related=[articles.clinicLocalSeo,articles.medicalSeo,articles.clinicVideo,articles.clinicReputation];

function useSeo(title,description,path){useEffect(()=>{document.title=title;let meta=document.querySelector('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.appendChild(meta)}meta.content=description;let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=`${BASE}${path}`},[title,description,path])}

function clinicName(page){return page.h1.replace('Websites and Marketing for ','').replace('Marketing for ','')}
function Hero({page,hub=false}){return <section className="hm-hero"><div className="container"><nav className="hm-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>→</span>{hub?<span>Healthcare Marketing</span>:<><Link to="/healthcare-marketing/">Healthcare Marketing</Link><span>→</span><span>{clinicName(page)}</span></>}</nav><h1>{page.h1}</h1><p>{page.description}</p><div className="hm-actions"><Link className="btn" to="/contact/#contact-enquiry">Discuss Your Clinic’s Needs</Link>{hub&&<a href="#clinic-types">Explore Clinic Types</a>}</div></div></section>}

function Services({order=[0,1,2,3,4,5]}){return <section className="hm-section hm-services" aria-labelledby="hm-services-title"><div className="container"><span className="hm-label">Healthcare marketing services</span><h2 id="hm-services-title">Practical support for your clinic’s priorities</h2><div className="hm-service-grid">{order.map(index=>{const [title,copy,path]=services[index];return <Link to={path} key={`${title}-${index}`}><h3>{title}</h3><p>{copy}</p><span aria-hidden="true">→</span></Link>})}</div></div></section>}

function Process(){return <section className="hm-section hm-process" aria-labelledby="hm-process-title"><div className="container"><h2 id="hm-process-title">From your clinic’s priorities to a working website and content plan</h2><div className="hm-process-grid">{process.map(([number,title,copy])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>}

function Faq({specific}){const faqs=specific?[...commonFaqs,specific]:commonFaqs;return <section className="hm-section hm-faq" aria-labelledby="hm-faq-title"><div className="container"><h2 id="hm-faq-title">Frequently asked questions</h2><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>}

function Related(){return <section className="hm-section hm-related" aria-labelledby="hm-related-title"><div className="container"><h2 id="hm-related-title">Related Articles</h2><ul>{related.map(([title,path])=><li key={path}><a href={path}>{title}</a></li>)}</ul></div></section>}

function Final(){return <section className="hm-section hm-final" aria-labelledby="hm-final-title"><div className="container"><div><h2 id="hm-final-title">What would make your clinic’s website more useful?</h2><p>Share your website and the improvements you have in mind. The conversation can cover design, local visibility, content, booking information or administrative workflows.</p><Link className="btn" to="/contact/#contact-enquiry">Discuss Your Clinic’s Needs</Link></div></div></section>}

function ClinicNav({current}){const links=Object.entries(pages).filter(([slug])=>slug!==current).map(([slug,page])=>[clinicName(page),`/healthcare-marketing/${slug}/`]);return <nav className="hm-clinic-nav" aria-label="Clinic marketing pages"><div className="container"><strong>Healthcare Marketing</strong><div>{links.map(([name,path])=><Link to={path} key={path}>{name}</Link>)}</div></div></nav>}

export function HealthcareMarketingHub(){const page={h1:'Healthcare Marketing for Clinics and Providers',description:'Help people find your clinic, understand your services, and know how to get in touch. Magneo brings together website design, local SEO, educational content, video and marketing automation around your clinic’s services, capacity and goals.'};useSeo('Healthcare Marketing & Website Design | Magneo','Healthcare marketing for clinics and providers, including website design, local SEO, educational content, video, campaigns, and administrative automation.','/healthcare-marketing/');const clinics=[['Mental health','Clear information about practitioners, services and how to take the first step.','mental-health-clinics'],['Chiropractic','Local visibility, first-visit information and straightforward booking options.','chiropractic-clinics'],['Family medicine','Useful websites and clear communication for new and existing patients.','family-medicine-clinics'],['Aesthetic','Treatment education, practitioner profiles and consultation enquiries.','aesthetic-clinics'],['Physiotherapy','Service information, local discovery and assessment bookings.','physiotherapy-clinics'],['Dental','Practice websites, local search and information for prospective patients.','dental-clinics']];return <div className="hm-page"><Hero page={page} hub/><section className="hm-section hm-fit" aria-labelledby="hm-fit-title"><div className="container"><h2 id="hm-fit-title">Marketing that fits how your clinic operates</h2><div>{[['Attract new patients','Local search, service pages and targeted campaigns help introduce your clinic when there is capacity for new bookings.'],['Support referral enquiries','Clear service information, practitioner profiles and referral instructions help patients and referring professionals understand how to contact your clinic.'],['Improve patient information','Make booking options, opening hours, locations and common questions easy to find, including when new-patient intake is limited.']].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section id="clinic-types" className="hm-section hm-clinics" aria-labelledby="hm-clinics-title"><div className="container"><h2 id="hm-clinics-title">Explore marketing for your clinic</h2><div>{clinics.map(([title,copy,slug])=><Link to={`/healthcare-marketing/${slug}/`} key={slug}><h3>{title}</h3><p>{copy}</p><span aria-hidden="true">→</span></Link>)}</div></div></section><Services/><Process/><Faq/><Related/><Final/></div>}

export function HealthcareSpecialistPage({slug}){const page=pages[slug];useSeo(page.title,page.meta,`/healthcare-marketing/${slug}/`);return <div className="hm-page"><Hero page={page}/><section className="hm-section hm-focus" aria-labelledby="hm-focus-title"><div className="container"><h2 id="hm-focus-title">{page.heading}</h2><div>{page.cards.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><Services order={page.serviceOrder}/><Process/><Faq specific={page.faq}/><ClinicNav current={slug}/><Related/><Final/></div>}
