import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { articles } from './data/related-articles.js';
import './styles/technology-marketing-pages.css';

const BASE='https://magneo.ca';

const services=[
  ['Website design and product messaging','Product websites, use-case pages and clear copy that explain your offering and help visitors find the next step.','/services/website-design-for-tech-companies-saas-products-magneo/'],
  ['SEO and content','Search research, technical improvements, articles and product content built around relevant customer questions.','/services/seo-for-regulated-industries/'],
  ['Product video and social media','Walkthroughs, explainers, Reels, founder interviews and social content adapted to the selected platforms.','/services/social-media-linkedin-leadership-for-tech-saas-ai-companies-magneo/'],
  ['AI brand voice and content workflows','A custom GPT and editorial guidance can support a consistent brand voice. Approved sources and review steps help your team create content regularly.','/services/ai-content-marketing/'],
  ['Paid campaigns and landing pages','Campaign creative and focused pages connect a specific offer with a relevant enquiry, demo or signup action.','/services/ppc-landing-pages-for-regulated-industries/'],
  ['CRM implementation and follow-up','CRM setup, contact routing, email sequences and reporting help the team organise and follow up on incoming interest.','/services/ai-marketing-automation-for-tech-saas-ai-companies-magneo/']
];

const process=[
  ['01','Understand the product','Your audience, product capabilities and business priorities establish the direction.'],
  ['02','Plan the message and content','The plan identifies the pages, creative materials and channels needed to explain and promote your offering.'],
  ['03','Create and launch','Copy, design, video and campaigns move through clear review points before publication.'],
  ['04','Review and improve','Reporting helps identify which content and campaigns support the agreed goals and where changes are needed.']
];

const sharedFaqs=[
  ['Can you work with our existing website and marketing team?','Yes. The project can improve selected pages, create content or support campaigns alongside your existing team. A full rebuild is not required for every engagement.'],
  ['Can you create content from our product demonstrations?','Yes. Recorded walkthroughs, interviews and approved product information can become videos, articles, social posts and website content.'],
  ['Do you use AI in content production?','Yes. AI can support research organisation, drafting, repurposing and creative production. Product knowledge, real demonstrations and human review keep the content grounded in your business.'],
  ['Can you connect enquiries with our CRM?','Yes. CRM setup and integrations can help organise incoming enquiries, assign follow-up and track their progress. The implementation depends on the systems involved.']
];

const pages={
  'saas-marketing':{
    title:'SaaS Marketing Agency | Websites, SEO & Video | Magneo',meta:'SaaS marketing with clear product messaging, SEO, demo videos, landing pages and CRM follow-up. Help prospective customers understand and explore your software.',h1:'Marketing for SaaS Companies',description:'Show potential customers how your software fits their work. Clear product messaging, useful search content, demo videos and focused landing pages support trial signups, demo requests and informed conversations.',heading:'Make the value of your software easier to see',cards:[['Product and use-case pages','Explain the problems your software addresses, the people it serves and how its features work together. Give each important use case a clear place on your website.'],['Trial and demo pages','For trials, explain what is included and how to start. For demos, explain what visitors will see and make the request process straightforward.'],['Product videos and launch content','Turn real product walkthroughs into demo clips, tutorials, feature announcements, Reels and longer videos.'],['Email and CRM follow-up','Connect enquiries and trial interest with relevant emails, assigned follow-up and useful product information.']],faq:['Can you support both free trials and sales demos?','Yes. Each option can have its own page, message and next step. Visitors should understand what they can try independently and when a conversation with your team would be useful.'],faqIndexes:[0,1,3],serviceOrder:[0,1,2,4,5,3]
  },
  'fintech-marketing':{
    title:'FinTech Marketing Agency | Product Websites & Content | Magneo',meta:'FinTech marketing for financial technology products: websites, product explainers, SEO, video, landing pages and enquiry follow-up.',h1:'Marketing for FinTech Companies',description:'Make your financial technology easier to understand. Product websites, explainers, search content and campaigns help customers explore how your platform works, who it serves and how to get started.',heading:'Explain the product before asking people to sign up',cards:[['Clear product information','Bring features, supported uses, pricing information and onboarding steps together in language your audience can understand.'],['Content for the right customer','Give business buyers information about workflows, integrations and implementation. Give consumer audiences clear explanations of the product and signup process.'],['Product demonstrations','Show real interfaces and practical examples through walkthroughs, short videos and visual explainers.'],['Campaigns and follow-up','Connect each campaign to a relevant product page, enquiry form or signup destination, with CRM follow-up where appropriate.']],faq:['Can you market a FinTech product to businesses and consumers?','Yes. The website and campaigns can separate these audiences, with different examples, explanations and next steps. The content should match the product available to each group.'],faqIndexes:[0,1,3],serviceOrder:[0,2,1,4,5,3]
  },
  'legaltech-marketing':{
    title:'LegalTech Marketing Agency | Websites & Product Content | Magneo',meta:'LegalTech marketing through product websites, SEO, demo videos and campaigns that explain software to law firms and legal departments.',h1:'Marketing for LegalTech Companies',description:'Show legal teams how your software fits their daily work. Product websites, practical demonstrations and focused content explain your platform’s features, implementation and value to law firms and legal departments.',heading:'Connect software features with the work of legal teams',cards:[['Practical use cases','Explain the tasks your product supports, such as document workflows, matter management or client intake, using examples relevant to the actual product.'],['Product evaluation content','Make integration information, implementation steps, training options and verified security details easy to find.'],['Demonstrations and expert content','Create walkthroughs, product videos and articles that answer questions from prospective users and decision-makers.'],['Demo campaigns','Build focused landing pages and supporting content around a specific product use case and a clear demo invitation.']],faq:['How is LegalTech marketing different from law-firm marketing?','LegalTech marketing explains software to its prospective users and buyers. The focus is on product capabilities, workflows, implementation and adoption. Law-firm marketing promotes legal services to prospective clients.'],faqIndexes:[0,1,3],serviceOrder:[0,2,1,4,5,3]
  },
  'crypto-marketing':{
    title:'Crypto & Web3 Marketing Agency | Content & Video | Magneo',meta:'Marketing for crypto and Web3 products through clear websites, educational content, product videos, social media and launch campaigns.',h1:'Marketing for Crypto and Web3 Companies',description:'Give people a clear explanation of your product and a reason to explore it. Websites, educational videos, social content and launch campaigns introduce your platform, explain its uses and support an informed community.',heading:'Build the story around what people can use',cards:[['Product and ecosystem explanations','Explain what the platform does, who it serves and how its main features fit together.'],['X and community content','Create product updates, educational threads, launch content and answers to recurring community questions.'],['YouTube and short-form video','Turn walkthroughs and product explanations into tutorials, longer videos and short clips adapted for each channel.'],['Launch and onboarding content','Connect announcements with useful landing pages, guides and clear instructions for getting started.']],faq:['Does the strategy focus only on social media?','No. Social content can work alongside a product website, searchable guides, video tutorials and launch pages. The channel mix follows the product and the audience the project needs to reach.'],faqIndexes:[0,1,2],serviceOrder:[2,0,1,3,5,4]
  },
  'ai-marketing':{
    title:'Marketing for AI Companies & Products | Magneo',meta:'Marketing for AI companies through clear positioning, product websites, SEO, real demonstrations, video content and campaigns for relevant use cases.',h1:'Marketing for AI Companies',description:'Show customers what your AI product can do in practical terms. Clear positioning, real demonstrations, use-case pages and educational content help people understand where it fits and how to try it.',heading:'Make the product understandable through real examples',cards:[['Specific use-case pages','Explain the task, the intended user and how the product supports the work, with examples grounded in actual capabilities.'],['Real product demonstrations','Show the product in action through walkthroughs, tutorials, demo clips and clear explanations of the output.'],['Search and educational content','Answer the questions prospective customers ask when comparing tools, exploring integrations or evaluating a new workflow.'],['Launch and founder content','Turn product expertise into launch materials, interviews, short videos and consistent social content.']],faq:['Is this marketing for AI companies or marketing using AI?','This service is for companies selling AI products and services. The focus is on explaining and promoting your offering.','Magneo also provides AI-powered content and marketing services for businesses in other industries.'],faqIndexes:[0,1,2],serviceOrder:[0,2,1,3,4,5]
  }
};

export const technologySpecialistSlugs=Object.keys(pages);
const related=[articles.productLed,articles.microSaas,articles.saasCommunity,articles.aiPersonalization];

function useSeo(title,description,path){useEffect(()=>{document.title=title;let meta=document.querySelector('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.appendChild(meta)}meta.content=description;let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=`${BASE}${path}`},[title,description,path])}

function productName(page){return page.h1.replace('Marketing for ','').replace(' Companies','')}
function Hero({page,hub=false}){return <section className="tm-hero"><div className="container"><nav className="tm-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>→</span>{hub?<span>Technology Marketing</span>:<><Link to="/tech-company-marketing/">Technology Marketing</Link><span>→</span><span>{productName(page)}</span></>}</nav><h1>{page.h1}</h1><p>{page.description}</p><div className="tm-actions"><Link className="btn" to="/contact/#contact-enquiry">Discuss Your Product</Link>{hub&&<Link to="/portfolio/#ai-marketing">Explore Our Work</Link>}</div></div></section>}

function Services({order=[0,1,2,3,4,5]}){return <section className="tm-section tm-services" aria-labelledby="tm-services-title"><div className="container"><span className="tm-label">Technology marketing services</span><h2 id="tm-services-title">Choose the support your product needs</h2><div className="tm-service-grid">{order.map(index=>{const [title,copy,path]=services[index];return <Link to={path} key={`${title}-${index}`}><h3>{title}</h3><p>{copy}</p><span aria-hidden="true">→</span></Link>})}</div></div></section>}

function Work(){return <section className="tm-section tm-work" aria-labelledby="tm-work-title"><div className="container"><div><span className="tm-label">Original Magneo concepts and demonstrations</span><h2 id="tm-work-title">See how the work comes together</h2><p>Explore examples of website design, social content, video formats, and AI-assisted marketing. The portfolio examples are concepts and demonstrations, not claimed technology client results.</p><div><Link to="/portfolio/#social-media">Explore content and video examples <span aria-hidden="true">→</span></Link><Link to="/portfolio/#ai-marketing">Explore AI marketing examples <span aria-hidden="true">→</span></Link></div></div></div></section>}

function Process(){return <section className="tm-section tm-process" aria-labelledby="tm-process-title"><div className="container"><h2 id="tm-process-title">From product understanding to published work</h2><div className="tm-process-grid">{process.map(([number,title,copy])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>}

function Faq({page}){const faqs=page?page.faqIndexes.map(index=>sharedFaqs[index]).concat([page.faq]):sharedFaqs;return <section className="tm-section tm-faq" aria-labelledby="tm-faq-title"><div className="container"><h2 id="tm-faq-title">Frequently asked questions</h2><div>{faqs.map(([question,answer,linkCopy])=><details key={question}><summary>{question}</summary><p>{answer}{linkCopy&&<> <Link to="/services/ai-powered-digital-marketing/">{linkCopy}</Link></>}</p></details>)}</div></div></section>}

function Related(){return <section className="tm-section tm-related" aria-labelledby="tm-related-title"><div className="container"><h2 id="tm-related-title">Related Articles</h2><ul>{related.map(([title,path])=><li key={path}><a href={path}>{title}</a></li>)}</ul></div></section>}

function Final(){return <section className="tm-section tm-final" aria-labelledby="tm-final-title"><div className="container"><div><h2 id="tm-final-title">What does your product need next?</h2><p>A clearer website, a product launch, regular content or better follow-up? Share your priorities and current setup to discuss a practical scope.</p><Link className="btn" to="/contact/#contact-enquiry">Discuss Your Product</Link></div></div></section>}

function ProductNav({current}){const links=Object.entries(pages).filter(([slug])=>slug!==current).map(([slug,page])=>[productName(page),`/tech-company-marketing/${slug}/`]);return <nav className="tm-product-nav" aria-label="Technology marketing pages"><div className="container"><strong>Technology Marketing</strong><div>{links.map(([name,path])=><Link to={path} key={path}>{name}</Link>)}</div></div></nav>}

export function TechnologyMarketingHub(){const page={h1:'Digital Marketing for Technology Companies',description:'Make your product easier to understand and give potential customers a clear reason to explore it. Magneo creates websites, search content, product videos, campaigns and automated follow-up for technology companies.'};useSeo('Technology Marketing Agency | Websites, SEO & Content | Magneo','Marketing for technology companies: product websites, SEO, video, social content, paid campaigns and CRM automation for SaaS, FinTech, LegalTech and AI.','/tech-company-marketing/');const products=[['SaaS','Product websites, search content and campaigns supporting trials, demos and customer onboarding.','saas-marketing'],['FinTech','Clear explanations of financial products, features and onboarding for consumers or business customers.','fintech-marketing'],['LegalTech','Product demonstrations and content that connect software features with the work of legal teams.','legaltech-marketing'],['Crypto','Product education, community content and launch materials for blockchain products and platforms.','crypto-marketing'],['AI companies','Use-case pages, demonstrations and content that explain what your AI product can actually do.','ai-marketing']];return <div className="tm-page"><Hero page={page} hub/><section className="tm-section tm-value" aria-labelledby="tm-value-title"><div className="container"><h2 id="tm-value-title">From explaining your product to supporting the next step</h2><div>{[['A clearer product story','Positioning, website copy and use-case pages explain who your product helps, what it does and why it matters.'],['Content people can discover','SEO content, product videos and social campaigns introduce your product through the questions your audience asks.'],['Easier enquiries and follow-up','Landing pages, demo forms, signup links and CRM workflows connect interest with a practical next step.']].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="tm-section tm-products" aria-labelledby="tm-products-title"><div className="container"><h2 id="tm-products-title">Marketing for your type of technology</h2><div>{products.map(([title,copy,slug])=><Link to={`/tech-company-marketing/${slug}/`} key={slug}><h3>{title}</h3><p>{copy}</p><span aria-hidden="true">→</span></Link>)}</div></div></section><Services/><Work/><Process/><Faq/><Related/><Final/></div>}

export function TechnologySpecialistPage({slug}){const page=pages[slug];useSeo(page.title,page.meta,`/tech-company-marketing/${slug}/`);return <div className="tm-page"><Hero page={page}/><section className="tm-section tm-focus" aria-labelledby="tm-focus-title"><div className="container"><h2 id="tm-focus-title">{page.heading}</h2><div>{page.cards.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><Services order={page.serviceOrder}/><Work/><Process/><Faq page={page}/><ProductNav current={slug}/><Related/><Final/></div>}
